### ISSUE TITLE
Hi, Nice work! Is it possible to display the pictures referred by the persons?

### ISSUE THREAD

**Issue by vilisch** [PeWu/topola-viewer#1]

**Comment by PeWu** [comment]
Hi,

Displaying pictures is possible, although it is not fully supported. There are 2 ways to do it.

1. Make sure the GEDCOM file contains absolute URL links to pictures, i.e. in the format `https://.../...jpg`. Example entry in GEDCOM:
```
1 OBJE
2 FILE https://example.org/image.jpg
```

2. When opening a GEDCOM file using the "Open file" menu, select multiple files at once – the .ged file together with .jpg files containing pictures. This is an undocumented feature and it may or may not work properly. You can still give it a try.

Please let me know if it worked.

**Comment by vilisch** [comment]
Hi Przemek,


Thanks for your answer.
I tried both solutions but unfortunately none of them is working. I
prepared a very simple test file (you can find it attached), maybe you have
time to take a look in and find out what is wrong.

For remote I used these files:
http://www.studio7.ro/test/TestPicture.png
http://www.studio7.ro/test/Test.ged

For local files I used the attached ones.

Regards,
Vilmos

**Comment by PeWu** [comment]
I made a fix. Topola supported only OBJEcts inlined in the INDI record and not linked records.

Please try opening your files with the "Open file" menu selecting your ged file together with the images.

**Comment by vilisch** [comment]
I tested and it is working well with local files.
Thanks.
