### ISSUE TITLE
Does not properly handle inter-family marriages

### ISSUE THREAD

**Issue by brendonky18** [PeWu/topola-viewer#106]
In my family tree two of my ancestors were cousins that were married and had children together. 

In gramps, this is represented as follows:
![image](https://user-images.githubusercontent.com/20930961/176018202-2d64eca7-c3a2-4563-a917-363aa5a1c276.png)

However, this visualizer creates two separate trees
![image](https://user-images.githubusercontent.com/20930961/176018351-1114083a-acaf-4543-ab50-5a48c538b667.png)

Essentially, it creates two instances of the same tree. 

Obviously not the end of the world, but it would certainly be less confusing if it could handle this edge case more gracefully.

**Comment by endolith** [comment]
Duplicate of https://github.com/PeWu/topola-viewer/issues/30 ?

**Comment by PeWu** [comment]
Thanks Brendon for the report. This has been an open issue for quite a long time and I still haven't figured out how to reasonably handle it. Suggestions are more than welcome :-)

Duplicate of https://github.com/PeWu/topola-viewer/issues/30
