### ISSUE TITLE
Make it possible to hide the ID

### ISSUE THREAD

**Issue by KentGrigo** [PeWu/topola-viewer#116]
The rendition of the family tree is so clean (thank you for making it!) that it's a shame that the ID has to be shown.
If possible, I'd like a way of hiding the ID.

**Comment by KentGrigo** [comment]
This PR makes it possible to toggle the IDs: https://github.com/PeWu/topola-viewer/pull/131

**Comment by KentGrigo** [comment]
@PeWu, I've noticed that people commit directly to this repo, without doing a PR.
Would you prefer if I did the same?

**Comment by PeWu** [comment]
Fixed in #131 
The change is already live in the published version.
Thank you @KentGrigo for the contribution
