### ISSUE TITLE
URL opening do not work

### ISSUE THREAD

**Issue by Czajkor** [PeWu/topola-viewer#123]
Hello.
First of all, huge thanks for your work. Recently I ran into the issue, where opening Google Drive links do not work, while they did in not-so-distant past. When I click on https://topola-cors.herokuapp.com the error message appears, stating, that:
Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail

Thanks in advance for solving this issue.

**Comment by PeWu** [comment]
This is happening because Heroku [turned down their free plan](https://blog.heroku.com/next-chapter) and Topola Viewer is using a CORS proxy to access files on the Web.

A solution will be published very soon – moving from Heroku to a different provider.

**Comment by Czajkor** [comment]
Thank you for clarification.
Once again thank you for such a magnificent tool
