### ISSUE TITLE
Hide sex

### ISSUE THREAD

**Issue by KentGrigo** [PeWu/topola-viewer#138]
Now that it's possible to hide the ID (https://github.com/PeWu/topola-viewer/issues/116), it would also be nice to be able to hide the sex.
The information is often given by the position of the person in the graph, and this information takes up an entire line by itself when the ID is not shown.

How I see a solution to this issue:
- Add `hideSex` to [Topola](https://github.com/PeWu/topola): \[[Commit for hiding IDs](https://github.com/PeWu/topola/commit/519626ee959a218a7df2bdcbbde0e29f4b4bdc52)\]
- Adjust height based on whether the ID and sex is shown in [Topola](https://github.com/PeWu/topola)
- Add setting to hide the sex in [Topola Viewer](https://github.com/PeWu/topola-viewer): \[[Commit for hiding IDs](https://github.com/PeWu/topola-viewer/pull/131/commits/70fe6c98cbb6f47337a7535f50944cdbfbd4c4c3)\]
- Make it possible to toggle `hideSex` in [Topola Viewer](https://github.com/PeWu/topola-viewer): \[[Commit for hiding IDs](https://github.com/PeWu/topola-viewer/pull/131/commits/54560854b2ff0b5a07f00b9887aac56717e9ffd2)\]

**Comment by PeWu** [comment]
Sounds like a good idea. If you'd like to contribute, I'd be happy to merge pull requests.

**Comment by KentGrigo** [comment]
Sounds great! 
Here's the first PR: https://github.com/PeWu/topola/pull/56
