### ISSUE TITLE
Tree not showing correctly

### ISSUE THREAD

**Issue by ch1zra** [PeWu/topola-viewer#15]
Hi everyone,

great project, I love the simplicity and sleekness :)
I just started making my own tree, and luckily both parents of my wife and me had a lot of data on hand, so in no time I built a large tree. But loading it in Topola is not working properly, one entire branch is not displaying.
My GEDCOM:
REMOVED FOR PRIVACY REASONS

Problem is that when selecting person I0206 his parents (I0307 and I0448) are not shown.
Any ideas what is causing this?
I am using Gramps and I have tried repairing tree and re-exporting, but problem persists. Gramps is showing everything just fine.

Thanks in advance.

**Comment by shpultik** [comment]
my guess, something is wrong in your data(maybe duplicated families, while creating)
parents(I0307 and I0448) are in family  FAMS @F0120@
and person(I0206) - is as child in families 1 FAMC @F0118@ 1 FAMC @F0120@ 

so i removed in this person two pointed lines
0 @I0206@ INDI
1 NAME Zvonimir /Štolba/
2 GIVN Zvonimir
2 SURN Štolba
1 SEX M
1 BIRT
2 DATE 24 APR 1930
1 DEAT
2 DATE 14 JAN 2005
- **1 FAMC @F0118@**
- **2 PEDI birth**

1 FAMC @F0120@
2 PEDI birth
1 FAMS @F0100@
1 CHAN
2 DATE 17 MAY 2020
3 TIME 18:45:57

and now shows this person parents. as it should be.

**Comment by ch1zra** [comment]
> my guess, something is wrong in your data(maybe duplicated families, while creating)
> parents(I0307 and I0448) are in family FAMS @F0120@
> and person(I0206) - is as child in families 1 FAMC @F0118@ 1 FAMC @F0120@
> 
> so i removed in this person two pointed lines
> 0 @I0206@ INDI
> 1 NAME Zvonimir /Štolba/
> 2 GIVN Zvonimir
> 2 SURN Štolba
> 1 SEX M
> 1 BIRT
> 2 DATE 24 APR 1930
> 1 DEAT
> 2 DATE 14 JAN 2005
> 
> * **1 FAMC @F0118@**
> * **2 PEDI birth**
> 
> 1 FAMC @F0120@
> 2 PEDI birth
> 1 FAMS @F0100@
> 1 CHAN
> 2 DATE 17 MAY 2020
> 3 TIME 18:45:57
> 
> and now shows this person parents. as it should be.

Thanks. So I need to do some tidying of my data. Sorry for false alarm.
