### ISSUE TITLE
can't view a tree from a URL anymore

### ISSUE THREAD

**Issue by rosland** [PeWu/topola-viewer#155]
Apologies for putting this to the wrong place. 
I find myself unable to view a tree from a URL or two  that I have used for a few years (but not in the last few months). 
One of them is:
https://apps.wikitree.com/apps/wiech13/topola-viewer/#/view?gen=-2&indi=P5&url=chall.us/challtree.ged
 I'm getting "failed to load file" "failed to fetch."  I tried adding  https://  or http://, but it had worked as is in the past. 
 
The GED file is fine, and I can view it in a browser.   I also can view the tree if I manually upload the file.  But I want to share the tree with others, with the GED stored on my personal website, and that used to work.

**Comment by BarrySilic** [comment]
I am getting the same issue.

**Comment by uhaud** [comment]
The same problem. I tried with GEDCOM file in my own server and in Google Drive, as explained in ReadMe, but when opening the URL the only result is the notice "failed to load file".

**Comment by mfaber** [comment]
Same here. Any solution yet? Or a workaround?

**Comment by napobo3** [comment]
The same problem when I am using my Wikitree ID : 

https://pewu.github.io/topola-viewer/#/view?indi=Kull-141&source=wikitree&standalone=true

Getting : 

**Failed to load file
Network request failed**

**Comment by PeWu** [comment]
I deployed the cors-anywhere proxy on a new server. I hope this time it's going to work for some time.
See also #130

**Comment by IstvanZachar** [comment]
I cannot access my Google Drive file. I followed the description in the Readme [here](https://github.com/PeWu/topola-viewer), but then the Viewer claims: "Failed to load file" without any further specification. The same ged file I can open without issues locally with Topola.
