### ISSUE TITLE
Images are missing in exported PNG-file

### ISSUE THREAD

**Issue by zkab** [PeWu/topola-viewer#161]
In GRAMPS I use Tools/Analysis and Exploration/Interactive Family Tree … I get the Topola Genealogy Viewer in a Firefox tab and it looks OK.
Then I search for a person in Topola and also I get the right person and it looks fine.
When I download a PNG-file then some person images are missing in that PNG-file.
How can this be fixed?
My default browser if Firefox.

**Comment by PeWu** [comment]
Thanks for the report. I couldn't reproduce this problem with my data. Could you help me reproduce it? Is it always failiing in the same way? Is it always the same images?
