### ISSUE TITLE
Making Gramps plugin available over the internet

### ISSUE THREAD

**Issue by aiq008** [PeWu/topola-viewer#17]
Hi
Is it possible to set it up so that i may use a hostname address that has port forwarding enabled on my router. That way anyone can view the Interactive Family tree, but i have to have Gramps Running. The example URL will be https://pewu.github.io/topola-viewer/#/view?utm_source=gramps&handleCors=false&standalone=false&url=http://myddnsname.net:8156
This would be a great help to allow other to view the tree.
Do you think it is doable?
Thanks

**Comment by PeWu** [comment]
Hi,

This is actually a security feature that you cannot do it and I would discourage trying to do it this way.

However, you can export the GEDCOM file from Gramps and host it either on a local web server. You can use any web server (e.g. [nginx](http://nginx.org/)) and do the same port forwarding setup as you did for Gramps. You can also host the GEDCOM file somewhere on the web for the same effect.

**Comment by aiq008** [comment]
Thanks. It worked perfectly
