### ISSUE TITLE
Localization to other language

### ISSUE THREAD

**Issue by PushKK** [PeWu/topola-viewer#21]
Can you localize Topola to other language?
I use Gramps (with date format 30.12.2019 and person name format "Surname (Notpatronymic) Given Patronymic") and see non-localization date in graph - "30 Dec 2019".
In Russian language this date must be "30.12.2019" or "30 Дек 2019".
And I see person's names in other format, not my. 

P.S. I see topola-viewer/src/translations/pl.json file, but it not have month names. I can translate this file to ru.json and send to you.
Additionally Gramps plugin must send to your server:
1. Language code (as example "ru"),
2. Date format,
3. Name format.

Gramps plugin: https://github.com/PushKK/addons-source/tree/master/Topola
It's my test fork.

P.P.S. My PR https://github.com/PeWu/topola-viewer/pull/22

**Comment by PeWu** [comment]
Thank you for offering to add the Russian translation. I commented on your PR regarding the translation and added a commit there.
Additionally, to complete the translation, there is one more place that requires changing. In a separate repository that contains the chart rendering code (https://github.com/PeWu/topola) there is one place that has translations for date qualifiers (before, after, etc.). You'd need to update `QUALIFIERS_I18N` in [src/date-format.ts](https://github.com/PeWu/topola/blob/master/src/date-format.ts) in that repository.

I'm not sure what you mean by the name format. Can you give an example? How do you enter the names into Gramps and how would you expect them to be displayed in Topola Viewer?

**Comment by PushKK** [comment]
Good day.

What change I see now:
1. When I use Topola from Gramps I not see right side panel with Person info (as on this):
https://gramps-project.org/wiki/index.php/Interactive_Family_Tree
One week ago this panel work fine.

2. I not see Russian language on:
https://apps.wikitree.com/apps/wiech13/topola-viewer/#/view?file=0f8acb865f1433a4cc7711af180b10fb&gen=-1&indi=7
https://pewu.github.io/topola-viewer/#/view?gen=-8&handleCors=false&indi=I0444&standalone=false&url=http%3A%2F%2F127.0.0.1%3A8156%2F&utm_source=gramps

3. I see Russian language (on dates only) on this site:
https://pewu.github.io/topola/upload
But one problem:
If date have day (DD.MM.YYYY) month must be in "Dopełniacz przypadek" (21 мая 2020).
If date not have day (MM.YYYY) month must be in "Mianownik przypadek" (Май 2020).

**Comment by PeWu** [comment]
Thank you for the translations. I deployed a new version containing the translations.

1. This was a bug. It is fixed now. Thanks for noticing.
2. Now the new version is deployed, you should see the translated app.
3. Thanks for pointing this out. I'll look how this can be fixed. Polish works similarly (21 maja 2020, maj 2020). However, when abbreviated month names are used, this is not an issue because abbreviated month names always have 3 letters, which is different for Russian.

**Comment by PushKK** [comment]
Yes, all sites show Russian language. Thank you.
I had see 3 nontranslated messages only:

![Снимок экрана_2020-09-10_15-23-39](https://user-images.githubusercontent.com/42420548/92736479-fd592f80-f382-11ea-8a49-defa1edc3fba.png)
![Снимок экрана_2020-09-10_15-26-36](https://user-images.githubusercontent.com/42420548/92736488-ff22f300-f382-11ea-9e99-8994cca64c77.png)
![Снимок экрана_2020-09-10_16-31-56](https://user-images.githubusercontent.com/42420548/92736751-385b6300-f383-11ea-850f-ba8a7a37d4c1.png)

**Comment by PushKK** [comment]
Good day.
Event "_MILT" not translated too.

I create new message on
https://gramps.discourse.group/t/topola-support-you-language-now/726
May be you can receive new PRs...

**Comment by PeWu** [comment]
I added translations for error messages coming out of Topola code. The _NetworkError..._ message is more tricky as it comes form the fetch API and can actually differ between browsers.
I added English and Polish translations for the _EDUC_, _FACT_ and _MILT_ GEDCOM tags. There are many more tags that are not translated though.
See [this commit](https://github.com/PeWu/topola-viewer/commit/6ec533461605fe158aeae922512ab4a8cbd988d3) for an example of how to add GEDCOM tag translations.

**Comment by PushKK** [comment]
I try add event's translations, but it not work.
I see - #67 is last work build. All newest build have error with 'React':

```
Treating warnings as errors because process.env.CI = true.
Most CI servers set it automatically.

Failed to compile.

./src/datasource/embedded.ts
  Line 13:6:  'EmbeddedMessageType' is defined but never used  @typescript-eslint/no-unused-vars
./src/chart.tsx
  Line 1:13:  'React' was used before it was defined  @typescript-eslint/no-use-before-define
./src/details.tsx
  Line 1:13:  'React' was used before it was defined  @typescript-eslint/no-use-before-define
./src/menu/menu_item.tsx
  Line 1:13:  'React' was used before it was defined  @typescript-eslint/no-use-before-define
./src/menu/search.tsx
  Line 1:13:  'React' was used before it was defined  @typescript-eslint/no-use-before-define
```

**Comment by PeWu** [comment]
I fixed these errors. They are false positives when running eslist code checks. It started happening after upgrading package versions.

**Comment by PushKK** [comment]
Yes, all work fine. Podziękować.
But all events in right panel (from Gramps) have order alphabetically - birth, chr, death, even, etc. It's wrong.
Events must be order by date - 1950, 1955, 1963, etc.
Can you change events order?

**Comment by PushKK** [comment]
Dobry dzień,
And not work Find (Search) function in Russian.
I can found person "John", but not found non-english names....

**Comment by PeWu** [comment]
Topola Viewer should now support Russian when using search.

**Comment by JiSva** [comment]
Hello PeWu.
I praise your program for its nice appearance and excellent functionality.
I tried to translate into Czech. I am attaching the cs.json file.
[cs.zip](https://github.com/PeWu/topola-viewer/files/6304274/cs.zip)

I see that the approximate dates are not translated in the graph. Applies to GEDCOM date modifiers: BEF, AFT, CAL. The date is also displayed differently, not in numbers but verbally (led = JANuar).
The date with modifier INT (Interpreted) is not displayed at all.   
![test](https://user-images.githubusercontent.com/82454215/114564837-fd9b0f80-9c70-11eb-8859-6ed6ed533c84.png)
