### ISSUE TITLE
Date issue after last update

### ISSUE THREAD

**Issue by ipalcic** [PeWu/topola-viewer#28]
Hi

I have noticed that after last update the date shows differently then before. Only few days ago it was DD MMMM YYYY (10 Oct 1574) and now out of the sudden it is showing MMMM, DD YYYY (Oct, 10. 1574). I am using topola via Gramps 5.1.3. and I didn't change anything in settings. 
 
Also I noticed that topola after last update started to automatically add "19" in year field if I have only two digits. For example I have only "14" so first two digits of the year of birth. Now, topola-viewer automatically added "19" and it shows "1914" instead on "14" (as in 15 century).

Additionally, I noticed that dates of birth and death are not aligned if one of the two is missing. This is especially visible with spouses. So if male has both dates and female only date of death then the birth day of male will be in the same line with the date of death of female. I believe that the same dates should be in the same line and not mixed up.

Hope that this can be fixed. I really love topola-viewer!
Thanks!
Best
Ivan

**Comment by PeWu** [comment]
Hi Ivan,

The date formatting behavior was changed in commit https://github.com/PeWu/topola/commit/b5477bf1e7179398408ab8e7063aa0b0e4a7e4d3. The default browser date formatting is used based on the language set inthe browser. I'm not sure this will work correctly in all situations. I may need to revert this change and look for a different way of formatting dates.
Anyway, why do you have only two digits of the year?

**Comment by ipalcic** [comment]
Hi PeWu

many thanks for your answer.  I use Google Chrome as a default browser but it has HR language as default so I don't understand why this happens. The same happens when I try it with Microsoft Edge. My computer also has HR language as default. I noticed that this change occurred in last 10 days maybe. In that period I didn't change anything. I think there was no update in Gramps in the meantime also. 
 
Regarding your question about the two digits, well I am not happy myself, but I am basing my family tree on a manuscript from late 18 century and there the author in some cases put only the first two digits of the year.

**Comment by PeWu** [comment]
With commit https://github.com/PeWu/topola-viewer/commit/ef5fe7502ae03db98ef0926ac9ee1bc8b008a327 the date issues should be fixed now.
