### ISSUE TITLE
'Download as PDF' fails for larger trees

### ISSUE THREAD

**Issue by waldemar-szostak** [PeWu/topola-viewer#3]
Exception
> jspdf.min.js:3306 Uncaught (in promise) Error: Supplied Data is not a valid base64-String jsPDF.convertStringToImageData 
    at Object.t.convertStringToImageData (jspdf.min.js:3306)
    at Object.t.addImage (jspdf.min.js:3263)
    at t.<anonymous> (chart.tsx:292)
    at c (runtime.js:45)
    at Generator._invoke (runtime.js:264)
    at Generator.t.<computed> [as next] (runtime.js:98)
    at r (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)

Browser: Chromium Wersja 76.0.3809.132 (Oficjalna wersja) Arch Linux (64-bitowa)

**Comment by PeWu** [comment]
Do you have reproduction steps?

The only error (warning actually) I was able to get is
> A page in a PDF can not be wider or taller than 14400 userUnit. jsPDF limits the width/height to 14400

together with a truncated image.

Unless there is a way to fix PDF generation, e.g. by using a different library, we should display a nice error message and not create corrupted files.

**Comment by waldemar-szostak** [comment]
1. Open a large tree such as https://drive.google.com/open?id=1z-Eh4VbdU5Ttib1d0aEUWTKwxouq4irB
2. Change the view to 'All relatives'
3. Download as PDF or PNG.

Results:
It fails quietly - only the JS console there's a trace of exceptions.
NOTE 1:
It does work downloading as SVG.

NOTE 2: 
It also does work for the default view (not the All relatives one).

Please let me know if I can be of any more assistance.

**Comment by PeWu** [comment]
Making it work would require changes in the underlying libraries or swapping out the libraries.
I made the app show a visual error when generating the graphics file fails.
I'm closing this issue now.
