### ISSUE TITLE
Load from URL results in "Forbidden"

### ISSUE THREAD

**Issue by hsynkrtl** [PeWu/topola-viewer#40]
Hi,

somehow load from URL stopped working. The URL is accessible and the file exists. It worked fine. Now it shows an error message "Forbidden"

Also the examples in the README show the same error.

Regards

**Comment by PeWu** [comment]
Topola Viewer used the CORS Anywhere service but the service got shut down: https://github.com/Rob--W/cors-anywhere/issues/301

We'll need to find an alternative solution.

**Comment by PeWu** [comment]
I fixed it by running the CORS anywhere code myself on Heroku. Let's see how far this will go.
