### ISSUE TITLE
UTF-8 characters not supported

### ISSUE THREAD

**Issue by Chiogros** [PeWu/topola-viewer#56]
Hi,
Thanks for this useful project.

The UTF-8 characters like é, è, ê, ù, ô... are displayed �.

**Comment by PeWu** [comment]
Hi,

UTF-8 should be supported. Do you have an example GEDCOM file that is displayed incorrectly?

**Comment by Chiogros** [comment]
Hi,

Sorry for the inconvenience, it seems that my exported GEDCOM file was ISO-8859-15 encoded.

Thanks!
