### ISSUE TITLE
Can't open .ged file from URL

### ISSUE THREAD

**Issue by PushKK** [PeWu/topola-viewer#59]
I try open gedcom file from Gramps project
https://github.com/gramps-project/gramps
on site
https://pewu.github.io/topola-viewer/#/

Full path to gedcom file
https://github.com/gramps-project/gramps/blob/master/example/gedcom/sample.ged

Can you check this?

**Comment by albertoriella** [comment]
> I try open gedcom file from Gramps project
> https://github.com/gramps-project/gramps
> on site
> https://pewu.github.io/topola-viewer/#/
> 
> Full path to gedcom file
> https://github.com/gramps-project/gramps/blob/master/example/gedcom/sample.ged
> 
> Can you check this?

This is because that link is an entire webpage and not a gedcom file.

You can obtain the gedcom file clicking "Raw" on github.
In this way you get this working link:
https://raw.githubusercontent.com/gramps-project/gramps/master/example/gedcom/sample.ged

**Comment by PushKK** [comment]
Thank you.
It's work/
