### ISSUE TITLE
Pass gedcom url as parameter

### ISSUE THREAD

**Issue by tasker25** [PeWu/topola-viewer#99]
If the topola viewer is embedded in another webpage, is there any way that the url of a gedcom could be passed when calling the topola webpage rather than the user entering it manually? I am not a programmer so not up to installing your code using npm.

I admired the forerunner of this visualiser in GenealogyJ and this is even better.

**Comment by PeWu** [comment]
Yes, you can pass the Gedcom URL as a URL parameter. For example:

https://pewu.github.io/topola-viewer/#/view?url=https%3A%2F%2Fwebtreeprint.com%2Ftp_downloader.php%3Fpath%3Dfamous_gedcoms%2Fshakespeare.ged

Notice how special characters are escaped. To make it easier, you can enter the gedcom URL using the "Open URL" menu and once then copy the URL from your browser.

In general, when you navigate a family tree, the URL will get updated. This means you can get a specific view encoded in the URL, not only the source Gedcom file.

**Comment by tasker25** [comment]
Thanks. I have got this working - https://www.burnelluk.info/topola.html

My gedcom contains no data on living individuals so privacy is not a concern.

**Comment by PeWu** [comment]
One more tip: add `&embedded=true` to the iframe's URL. You'll get only relevant menus (e.g. without _Open File_)

**Comment by tasker25** [comment]
Even better.
